[build]
  functions = "functions-build"
  command = "npm run build"

[dev]
  command = "npm run dev"
  framework = "#custom"

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/index"
  status = 200
